= MCGalaxyPlugins

This repository contains source codes for my MCGalaxy Plugins.

== Installing a plugin

*Requirement.* An MCGalaxy server, preferably version 1.9.4.3 or greater (I didn't test the plugins on earlier versions but they will most likely work on them).

Each plugin has its own folder. Let's say for instance that you want to install the Erosion plugin.

. In the *Plugins* section below, download `Erosion.cs` into your `mcgalaxy/plugins` folder.
. If your server isn't running already, run it (CLI or GUI, doesn't matter).
. Once the server is loaded, type `/pcompile Erosion` in the console. If this step causes an error, please post it in the issues section of this repository so that I can investigate it.
. Then, run `/pload Erosion` in the console.
. The plugin is now loaded. Connect to your server and run `/help erosion` to get started.

When restarting your server, the plugin will be loaded automatically.

== Plugins

=== BlockDBClean

Download link: link:https://raw.githubusercontent.com/dflat2/MCGalaxyPlugins/main/BlockDBClean/BlockDBClean.cs[BlockDBClean.cs]

Adds two commands `/BlockDBClean <map> <duration>` and `/BlockDBCleanAll <duration>` that removes all `/About` information older than given `duration`. Please note that `/BlockDBCleanAll` make take some time as it loads all levels one by one.

=== DotStatus

Download link: link:https://raw.githubusercontent.com/dflat2/MCGalaxyPlugins/main/DotStatus/DotStatus.cs[DotStatus.cs]

Displays zombie survival status when a player sends a message with a single `.` or a single `t`. To use it with lava survival instead, change the corresponding line in the plugin.

=== Erosion

Download link: link:https://raw.githubusercontent.com/dflat2/MCGalaxyPlugins/main/Erosion/Erosion.cs[Erosion.cs]

This plugin is inspired by erosion in binary image processing. It adds a new `/erode <mode> [block]` command that simulates erosion. It works by removing each `[block]` that is not surrounded by itself.

=== EasyFences

Download link: link:https://raw.githubusercontent.com/dflat2/MCGalaxyPlugins/main/EasyFences/EasyFences.cs[EasyFences.cs]

`/easyfences` (or its shorthand `/ezf`) guides you through the process of adding all blocks necessary to build Minecraft-like fences. Features:

* Ability to control the offsets of fence-elements (underground or above the posts)
* Generates as few blocks as necessary depending on your needs
* You can turn any block into a fence-set in less than a minute
* Decide whether players should be able to jump over the fences

Known issues:

* When using a texture pack with more than 256 textures (i.e. 512), fences' side textures  will be very likely wrong if fences are built from a block with either a low texture ID (less than 4) or a high texture ID (above 252).
* If you decide to bury fences, it's recommended to disable jumping over the fences, because collisions with barriers and corners sometimes go wrong.

=== SeeReportsOnLogin

Download link: link:https://raw.githubusercontent.com/dflat2/MCGalaxyPlugins/main/SeeReportsOnLogin/SeeReportsOnLogin.cs[SeeReportsOnLogin.cs]

Automatically runs `/Report list` when an operator joins.

=== Smooth

Download link: link:https://raw.githubusercontent.com/dflat2/MCGalaxyPlugins/main/Smooth/Smooth.cs[Smooth.cs]


=== InvincibleReferees

Download link: link:https://raw.githubusercontent.com/dflat2/MCGalaxyPlugins/main/InvincibleReferees/InvincibleReferees.cs[InvincibleReferees.cs]

Makes you invincible automatically when using `/Ref`.

=== NoCmdMode

Download link: link:https://raw.githubusercontent.com/dflat2/MCGalaxyPlugins/main/NoCmdMode/NoCmdMode.cs[NoCmdMode.cs]

MCGalaxy provides an easy way to unload commands from the `server.properties` file, but `/Mode` won't work, because the game will throw an error when doing `/<block>` (for example `/Lava`, `/Water`, etc.). This plugin will unload `/Mode` correctly by filtering out commands matching a block name.

== Commands

=== ConsoleDo

Download link: link:https://raw.githubusercontent.com/dflat2/MCGalaxyPlugins/main/Commands/Commands/CmdConsoleDo.cs[CmdConsoleDo.cs]

Runs a command as console while in-game.

=== LastModifiedLevels

Download link: link:https://raw.githubusercontent.com/dflat2/MCGalaxyPlugins/main/Commands/Commands/CmdLastModifiedLevels.cs[CmdLastModifiedLevels.cs]

Displays the last 10 modified levels. Note that it only takes blocks into account (ie. adding portals won't count as an update).

=== Smooth

Download link: link:https://raw.githubusercontent.com/dflat2/MCGalaxyPlugins/main/Commands/Commands/CmdSmooth.cs[CmdSmooth.cs]

A `/Smooth <block> <radius> [intensity]` command to smooth builds of `block`s.

